# Generated by Django 4.2.2 on 2023-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tienda',
        ),
        migrations.AddField(
            model_name='producto',
            name='tiendas',
            field=models.ManyToManyField(to='productos.tienda'),
        ),
    ]
