# Generated by Django 4.2.2 on 2023-06-29 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.ManyToManyField(to='productos.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda')),
            ],
        ),
    ]
